### ISSUE TITLE
建议回滚

### ISSUE THREAD

**Issue by Kuludu** [ZSCDumin/HunanUniversity#3]
学长你好，逛Github之中无意发现了这个仓库，感谢分享。
同时建议学长删除敏感资料的时候使用`git reset`回滚并强制同步而不是删除并commit，否则文件是可以被恢复的。
祝好！

**Comment by ZSCDumin** [comment]
哦哦，好的



---原始邮件---
发件人: "Kuludu"<notifications@github.com&gt;
发送时间: 2020年12月29日(周二) 下午4:25
收件人: "ZSCDumin/HunanUniversity"<HunanUniversity@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ZSCDumin/HunanUniversity] 建议回滚 (#3)




 
学长你好，逛Github之中无意发现了这个仓库，感谢分享。
 同时建议学长删除敏感资料的时候使用git reset回滚并强制同步而不是删除并commit，否则文件是可以被恢复的。
 祝好！
